### ISSUE TITLE
Make image more lightweight

### ISSUE THREAD

**Issue by alexanderadam** [afterlogic/docker-aurora-files#1]
[As you mentioned before](https://github.com/afterlogic/aurora-files/issues/9#issuecomment-618961444) it would make sense to make this image more lightweight.
Usually nginx uses much less resources than Apache (and it is often faster, too).

Also a smaller base image like [minideb](https://github.com/bitnami/minideb) or alpine would make the image more lightweight.

**Comment by afterlogic-support** [comment]
Good point, thank you, will look into that when time permits.

**Comment by afterlogic-support** [comment]
Just released an entirely new image, with Alpine and Nginx, as you proposed 👍
