### ISSUE TITLE
Release 9.0.1

### ISSUE THREAD

**Issue by extbe** [afterlogic/docker-aurora-files#11]
Hi.

Could you please upload an image with the new version and create the `9.0.1` tag?

Thanks!

**Comment by afterlogic-support** [comment]
Sure, just did that.

Most likely, we'll be updating other images of our products ([WebMail Lite](https://hub.docker.com/repository/docker/afterlogic/docker-webmail-lite) one, for example) using this image is a template.

Thank you!
