### ISSUE TITLE
No documentation on storage location

### ISSUE THREAD

**Issue by CvHorssen** [afterlogic/docker-aurora-files#13]
There is no documentation on where stuff is actually stored, so users would have to dive into the code to find out what volume(s) to map.

**Comment by afterlogic-support** [comment]
Thanks you for the suggestion.

Data directory is found at `/var/www/html/data` within the image. I believe there should be no need for users to map anything manually. And certainly, we don't know where stuff is actually sroted, that's up to Docker, all we can do is list the volumes in Dockerfile.

If you're willing to contribute to the product itself, the docker image or its documentation, we welcome that of course.
