### ISSUE TITLE
How to run https?

### ISSUE THREAD

**Issue by jonaskowalczyk** [afterlogic/docker-aurora-files#14]
Hello, 

I can I set docker compose to run aurora files with https?

Thank you for your help.

Jonáš Kowalczyk

**Comment by afterlogic-support** [comment]
Currently this isn't supported out-of-box, but both Aurora Files and Docker image are opensource so you can make any changes you require.

**NB:** this tracker is for reporting issues. If you require community support, please use our forum: https://s.afterlogic.com/forum/
