### ISSUE TITLE
Over Quota

### ISSUE THREAD

**Issue by HacKeD0x90** [afterlogic/docker-aurora-files#15]
Hello,

When I try to increase size for specific user I get below error.
Saving settings has failed. (Over quota)

Any idea how to override it or fix it?
I read that it's a known issue in old version but I have updated version.
Current Version attached.
![image](https://github.com/afterlogic/docker-aurora-files/assets/14231783/0e5e0170-6038-46d4-b482-a25a2a590908)

**Comment by afterlogic-support** [comment]
Have answered this at: https://github.com/afterlogic/aurora-files/issues/61
