### ISSUE TITLE
Don't use `root` user within the container

### ISSUE THREAD

**Issue by alexanderadam** [afterlogic/docker-aurora-files#2]
[It's best practice _not_ to use a `root` user if possible](https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#user) and switching to an unprivileged user with the `USER` command.

This will mean that you can't use port 80 within the container however. But this usually isn't an issue, as you can map the port from the outside.

**Comment by afterlogic-support** [comment]
Thank you, we will consider following that route.

**Comment by afterlogic-support** [comment]
Also, you're more than welcome to send a pull request with the changes you consider useful for the community.

**Comment by afterlogic-support** [comment]
The new image we've just released adopt the approach suggested. Thank you!
