### ISSUE TITLE
ENV variables `LOG_STDOUT` & `LOG_STDERR` look weird

### ISSUE THREAD

**Issue by alexanderadam** [afterlogic/docker-aurora-files#3]
[`ENV LOG_STDOUT **Boolean**`](https://github.com/afterlogic/docker-aurora-files/blob/59974052bea33a804fc810d963a636845d5367b9/Dockerfile#L27) doesn't look like it's intended like this. Are you sure this is how you wanted it to be? :thinking:

**Comment by afterlogic-support** [comment]
We used the code related to setting up LAMP environment from:
https://github.com/fauria/docker-lamp
And yes, that's intended. Still, as we're researching switching to a different environment (Nginx in particular) this will probably go away in the next update.
