### ISSUE TITLE
Any reason why you are using Ubuntu 16.04 as a base image?

### ISSUE THREAD

**Issue by alexanderadam** [afterlogic/docker-aurora-files#4]
You are [currently using Ubuntu 16.04](https://github.com/afterlogic/docker-aurora-files/blob/59974052bea33a804fc810d963a636845d5367b9/Dockerfile#L1) as a base image, [which will lose standard support next year](https://wiki.ubuntu.com/Releases#Current).

Is there any reason why you aren't using at least the current version 18.04 with LTS? :thinking: 

**PS:** this issue will obviously be obsolete [if you switch to another base image anyway](https://github.com/afterlogic/docker-aurora-files/issues/1).

**Comment by afterlogic-support** [comment]
We've encountered a couple of critical LAMP-related issues while trying to make it run with 18.04 but we're still working on it, 16.04 should be good enough for now - and yes you're quite right, switching to a different base image would resolve this, too.
