### ISSUE TITLE
[Question] How to work with VOLUME_HOME environment variable

### ISSUE THREAD

**Issue by extbe** [afterlogic/docker-aurora-files#5]
Hi!

In the `run-lamp.sh` there is a usage of environment variable `VOLUME_HOME` and I can't find the place where it is exported. As a result the database will be recreated every time a container starts. If I define this variable when starting the container, then database initialization is skipped every time the container starts.

https://github.com/afterlogic/docker-aurora-files/blob/59974052bea33a804fc810d963a636845d5367b9/run-lamp.sh#L40

**Comment by afterlogic-support** [comment]
Try adding the following line at the beginning of `run-lamp.sh`, right before `#!/bin/bash`:

```bash
VOLUME_HOME="/var/lib/mysql"
```

or define the following environment variable in `Dockerfile`:

```
ENV VOLUME_HOME "/var/lib/mysql"
```

**Comment by extbe** [comment]
Thanks for the answer!

If I define the variable, then `else` branch will be executed every time and MariaDB won't start because the start command is inside the `if` branch:

https://github.com/afterlogic/docker-aurora-files/blob/59974052bea33a804fc810d963a636845d5367b9/run-lamp.sh#L44

**Comment by afterlogic-support** [comment]
Understood, thank you. If you find a solution, please feel free to submit a pull request.

**Comment by extbe** [comment]
I'm trying to find a solution. Could you tell me the versions of PHP and MariaDB that should be used for the latest release of Aurora Files? I need them because the latest version of Aurora Files will be downloaded when we start building a Docker image:

https://github.com/afterlogic/docker-aurora-files/blob/59974052bea33a804fc810d963a636845d5367b9/Dockerfile#L40

**Comment by afterlogic-support** [comment]
For the latest v9, requirements are [as follows](https://afterlogic.com/docs/aurora-files/system-requirements):
PHP engine: 7.2.5 or newer
Database engine: MySQL 5.7.8 or newer / MariaDB 10.2.7 or newer

**Comment by extbe** [comment]
I made a fix for database recreation in scripts and  also upgraded dependencies. But I can't test the changes because I can't log in under `superadmin` with empty password. The system tells that `The username or password you entered is incorrect.`. Maybe something has changed in the code since the last docker build and we should also update the `afterlogic.php` file? 

Here are my recent changes, could you please take a look at them?
https://github.com/extbe/docker-aurora-files/tree/fix/database-initialization

**Comment by afterlogic-support** [comment]
In version 9, admin login is performed through a separate `/adminpanel/` entry point.
You can still use the old admin interface by logging in as superadmin from main page, that option wasn't removed from v9, was just disabled by default; to enable it, set **AllowLoginFromCoreModule** to **true** in `data/settings/modules/AdminAuth.config.json` configuration file.

If you can confirm the fix helps, please send a pull request. Thanks.

**Comment by extbe** [comment]
When pull request will be closed could you please update the image on DockerHub and create a separate tag with the version 9.0.0. Thanks!

**Comment by afterlogic-support** [comment]
We've accepted the pull request. Thank you for your great contribution! 
Will look into DockerHub update soon, too.
