### ISSUE TITLE
Override config values

### ISSUE THREAD

**Issue by extbe** [afterlogic/docker-aurora-files#8]
Hi.

After spending some time working with the latest version, I ran into the problem that there is no way to override the `/var/www/html/data/settings/config.json` values. For example, I want to set `EnableMultiTenant` eqal to `true`. I haven't found how to do this in the UI.

The root cause is the `VOLUMES` statement [here](https://github.com/afterlogic/docker-aurora-files/blob/e7ff50eda125affbbf6e16bc39187577338a9138/Dockerfile#L54). As per Docker documentation: 

> If any build steps change the data within the volume after it has been declared, those changes will be discarded.

So I won't be able to change the content of the `config.json` file in my Dockerfile.

Are there ways how to change config values in the UI?

**Comment by afterlogic-support** [comment]
While certain configuration parameters can indeed be set via admin interface, the majority of those can only be changed by editing the configuration files directly. And `data/settings/config.json` isn't the only configuration file of the product, every module has its own config under `data/settings/modules` directory, only a portion of those values can be changed via admin interface.
